version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.6

jobs:
  build:
    docker:
      - image: 'circleci/python:latest'

    steps:
      - checkout
      - aws-s3/sync:
          from: ./app/build
          to: '${TF_VAR_S3_BUCKET_URL}'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true